import { expect, test } from "bun:test";

const bun = Bun as typeof Bun & { file(path: string): { text(): Promise<string> } };
const readme = await bun.file("README.md").text();

const requiredTerms = [
  "bun run octosift -- dotfiles LuisUrrutia",
  "bun run octosift -- skills LuisUrrutia",
  "Every scan requires one search intent subcommand",
  "Built-in intents are `dotfiles` and `skills`",
  "owner/repo",
  "https://github.com/LuisUrrutia",
  "--file inputs.txt",
  "@inputs.txt",
  "--format csv",
  "--verbose",
  "--ignore-forks",
  "--max-contributors",
  "--max-repos",
  "--min-score",
  "--no-cache",
  "--cache-ttl <seconds>",
  "--config-dir <dir>",
  "TOML Search Intent Definitions",
  "search intent definition catalog",
  "./config",
  "lexicographic filename order",
  "same-name intent replaces the whole earlier definition",
  "Invalid TOML or invalid definition shape fails the command",
  "[[intent]]",
  "[[intent.exact_name]]",
  "[[intent.term_group]]",
  "normalization",
  "lowercase-separators",
  "fields may be `name`, `description`, and `topics`",
  "does not run formulas, JavaScript, shell commands, scripts",
  "72 hours",
  "259200 seconds",
  "--clear-cache",
  "exclusive commands",
  "--flag=value",
  "newline-delimited",
  "Blank lines are ignored",
  "Lines starting with `#` are ignored",
  "url",
  "owner",
  "name",
  "fullName",
  "description",
  "topics",
  "stars",
  "forks",
  "language",
  "isFork",
  "isArchived",
  "updatedAt",
  "pushedAt",
  "matchedSignals",
  "score",
  "sourceUser",
  "sourceInput",
  "JSON is the default output format",
  "sorted by `score` descending",
  "then by `pushedAt` descending",
  "Array fields are serialized with semicolons",
  "Search Intents And Scoring",
  "Strong signals add `+5`",
  "Medium signals add `+3`",
  "Weak signals add `+1`",
  "Exact repository names `dotfiles`, `.dotfiles`, `skill`, and `skills` add `+10`",
  "Forks add `-1`",
  "Archived repositories add `-2`",
  "only the highest-tier match counts",
  "default minimum output score is `3`",
  "metadata reports `size` as `0` are ignored",
  "type `Bot`",
  "GitHub Actions",
  "github-actions",
  "dependabot",
  "renovate",
  "claude",
  "copilot",
  "[bot]",
  "Authenticated `gh`",
  "`GH_TOKEN`",
  "`GITHUB_TOKEN`",
  "Unauthenticated GitHub REST",
  "rate limits will be lower",
  "`0`: success",
  "`1`: invalid input or configuration",
  "`2`: partial failure with usable output",
  "`3`: rate limit exhausted",
  "metadata-only",
  "agent skills",
  "Claude skills",
  "OpenCode skills",
  "AI agent workflows",
  "MCP skills",
  "Generic AI, devtool, tutorial",
  "README files",
  "repository content",
  "file trees",
  "branches",
  "GraphQL",
  "persistent cache",
  "~/.local/share/octosift/",
  "does not cache final filtered CLI output",
  "TUI",
  "recursive contributor expansion",
];

test("README documents required usage, schema, scoring, auth, and v1 limits", () => {
  for (const term of requiredTerms) {
    expect(readme).toContain(term);
  }
});

test("README stays practical and avoids disallowed docs scope", () => {
  expect(readme.includes("CI workflow")).toBe(false);
  expect(readme.includes("old package command name")).toBe(false);
  expect(readme.includes("package script has not been renamed")).toBe(false);
  expect(readme.includes(["eval", "("].join(""))).toBe(false);
});
